import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Admin Modules

  {
    path: "/admin/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },
  {
    path: "",
    title: "PARAMETER SETTINGS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },
  // {
  //   path: "",
  //   title: "Parameters",
  //   moduleName: "parameters",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_ADMIN"],
  //   submenu: [ ],
  // },
  {
    path: "/admin/departments",
    title: "Departments",
    moduleName: "departments",
    iconType: "feather",
    icon: "edit",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },

  {
    path: "",
    title: "TENDER COMMITTEE",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },

  {
    path: "",
    title: "Committee Members",
    moduleName: "add-user-to-committee",
    iconType: "feather",
    icon: "menu",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [
      {
        path: "/admin/committee-management/add-user-to-committe",
        title: "Add User To Committee",
        moduleName: "add-expense",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },

      {
        path: "/admin/committee-management/view-committee-members",
        title: "View Committee Members",
        moduleName: "view-committee-members",
        iconType: "feather",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  

  {
    path: "",
    title: "REPORTs",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },

  // {
  //   path: "/admin/contract-management/upload-contract-documents",
  //   title: "Create Evaluation Matrix",
  //   moduleName: "create-evaluation-matrix",
  //   iconType: "feather",
  //   icon: "check-circle",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_ADMIN"],
  //   submenu: [],
  // },

  // {
  //   path: "",
  //   title: "Bills",
  //   moduleName: "bills",
  //   iconType: "feather",
  //   icon: "book",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_ADMIN"],
  //   submenu: [
  //     {
  //       path: "/admin/bills/payment-confirmation-no-po",
  //       title: "Pay without PO",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/bills/active-bills",
  //       title: "Pay with PO",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },

  //     {
  //       path: "/admin/bills/pending-bills",
  //       title: "Pending bills",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/bills/rejected-bills",
  //       title: "Rejected bills",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/bills/paid-bills",
  //       title: "Paid bills",
  //       moduleName: "bills",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //   ],
  // },

  // **************************************************************************************************************
  // User Modules
  {
    path: "/user/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_USER"],
    submenu: [],
  },
  {
    path: "",
    title: "PURCHASE ORDER MANAGEMENT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["ROLE_USER"],
    submenu: [],
  },
  {
    path: "/user/supplier/categories-management",
    title: "Expense Categories",
    moduleName: "categories-management",
    iconType: "feather",
    icon: "menu",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_USER"],
    submenu: [],
  },
  {
    path: "/user/supplier/sub-categories-management",
    title: "Expense Subcategories",
    moduleName: "subcategories",
    iconType: "feather",
    icon: "layers",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_USER"],
    submenu: [],
  },

  {
    path: "/user/supplier/expenses-management",
    title: "Expenses",
    moduleName: "expenses-management",
    iconType: "feather",
    icon: "dollar-sign",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_USER"],
    submenu: [
      {
        path: "/user/supplier/expenses-management/add-expense",
        title: "Add Expense",
        moduleName: "add-expense",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/user/supplier/expenses-management/all",
        title: "View Expenses",
        moduleName: "view-expenses",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "/user/supplier/cost-centers-management",
    title: "Cost Centers",
    moduleName: "cost-centers-managemen",
    iconType: "feather",
    icon: "credit-card",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_USER"],
    submenu: [],
  },

  {
    path: "",
    title: "Suppliers Management",
    moduleName: "suppliers-management",
    iconType: "feather",
    icon: "sun",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_USER"],
    submenu: [
      {
        path: "/user/supplier/suppliers-management/add-supplier",
        title: "Add Supplier",
        moduleName: "add-supplier",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/user/supplier/suppliers-management/all",
        title: "View Suppliers",
        moduleName: "view-suppliers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "/user/supplier/cost-centers-management",
    title: "Cost Centers",
    moduleName: "cost-centers-managemen",
    iconType: "feather",
    icon: "credit-card",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["User"],
    submenu: [],
  },
  {
    path: "",
    title: "Purchase Orders",
    moduleName: "purchase-orders-management",
    iconType: "feather",
    icon: "shopping-bag",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_USER"],
    submenu: [
      {
        path: "/user/supplier/purchase-orders-management/create-purchase-order",
        title: "Add Purchase Order",
        moduleName: "view-purchase-orders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/user/supplier/purchase-orders-management/all",
        title: "View Purchase Orders",
        moduleName: "create-purchase-order",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  // {
  //   path: "/user/supplier/custom-bills-management/all-custom-bills",
  //   title: "Custom Bills Managament",
  //   moduleName: "custom-bills-management",
  //   iconType: "feather",
  //   icon: "briefcase",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_USER"],
  //   submenu: [],
  // },

  // {
  //   path: "",
  //   title: "INVOICE MANAGEMENT",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_USER", "ROLE_ADMIN"],
  //   submenu: [],
  // },

  // {
  //   path: "/user/customer/item-categories-management/all-item-categories",
  //   title: "Item Categories",
  //   moduleName: "stock-category",
  //   iconType: "feather",
  //   icon: "list",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_USER", "ROLE_ADMIN"],
  //   submenu: [],
  // },

  // {
  //   path: "",
  //   title: "Stock Management",
  //   moduleName: "items",
  //   iconType: "feather",
  //   icon: "shopping-cart",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_USER", "ROLE_ADMIN"],
  //   submenu: [
  //     {
  //       path: "/user/customer/items-management/add-item",
  //       title: "Add Commodity",
  //       moduleName: "add-customer",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/items-management/all-items",
  //       title: "All Commodities",
  //       moduleName: "add-customer",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/items-management/failed-ura-uploads",
  //       title: "Failed Uploads",
  //       moduleName: "failed-uploads",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //   ],
  // },

  // {
  //   path: "",
  //   title: "Customers Management",
  //   moduleName: "customers-management",
  //   iconType: "feather",
  //   icon: "grid",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_USER", "ROLE_ADMIN"],
  //   submenu: [
  //     {
  //       path: "/user/customer/customers-management/add-customer",
  //       title: "Add Customer",
  //       moduleName: "add-customer",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/customers-management/all-customers",
  //       title: "View Customers",
  //       moduleName: "view-customers",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //   ],
  // },
  // {
  //   path: "",
  //   title: "Invoice Management",
  //   moduleName: "invoice-management",
  //   iconType: "feather",
  //   icon: "file-text",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_USER", "ROLE_ADMIN"],
  //   submenu: [
  //     {
  //       path: "/user/customer/invoices-management/generate-invoice",
  //       title: "Generate Invoice",
  //       moduleName: "generate-invoice",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/invoices-management/pending-invoices",
  //       title: "Pending Invoices",
  //       moduleName: "pending-invoices",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/invoices-management/approved-invoices",
  //       title: "Approved Invoices",
  //       moduleName: "approved-invoices",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/invoices-management/rejected-invoices",
  //       title: "Rejected Invoices",
  //       moduleName: "rejected-invoices",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/invoices-management/uploaded-invoices",
  //       title: "Uploaded Invoices",
  //       moduleName: "uploaded-invoices",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/invoices-management/unsuccessful-ura-upload-invoices",
  //       title: "Unsuccessful Uploads",
  //       moduleName: "unsuccessful-invoices",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/user/customer/invoices-management/paid-invoices",
  //       title: "Paid Invoices",
  //       moduleName: "paid-invoices",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //   ],
  // },

  // *************************************************************************************************
  // More Admin modules
  // {
  //   path: "",
  //   title: "REPORTS",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_ADMIN"],
  //   submenu: [],
  // },
  {
    path: "/admin/reports/all",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "edit",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },

  //Head Of Departments
  //  {
  //   path: "",
  //   title: "REQUISITION OF NEED",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_HEAD", "ROLE_ADMIN"],
  //   submenu: [],
  // },

  // {
  //   path: "",
  //   title: "Need Management",
  //   moduleName: "user",
  //   iconType: "feather",
  //   icon: "umbrella",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_HEAD", "ROLE_ADMIN"],
  //   submenu: [
  //     {
  //       path: "/departmental-users/need-management/need-requisition-form",
  //       title: "Request Need",
  //       moduleName: "request-need",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/departmental-users/need-management/pending-needs",
  //       title: "Pending Needs",
  //       moduleName: "pending-needs",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/departmental-users/need-management/approved-needs",
  //       title: "Approved Needs",
  //       moduleName: "approved-needs",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/departmental-users/need-management/full-filled-needs",
  //       title: "Full Filled Needs",
  //       moduleName: "full-filled-need",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/departmental-users/need-management/rejected-needs",
  //       title: "Rejected Needs",
  //       moduleName: "rejected-needs",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //   ],
  // },

  {
    path: "",
    title: "ACCOUNTS & ROLES MANAGEMENT",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },
  {
    path: "/admin/roles",
    title: "Roles",
    moduleName: "roles",
    iconType: "feather",
    icon: "book",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },

  {
    path: "",
    title: "User Accounts",
    moduleName: "user",
    iconType: "feather",
    icon: "user",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [
      {
        path: "/admin/user-accounts/all",
        title: "Active Accounts",
        moduleName: "active-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/admin/user-accounts/inactive-accounts",
        title: "Inactive Accounts",
        moduleName: "inactive-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/admin/user-accounts/locked-accounts",
        title: "Locked Accounts",
        moduleName: "locked-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/admin/user-accounts/deleted-accounts",
        title: "Deleted Accounts",
        moduleName: "deleted-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/admin/user-accounts/add-account",
        title: "Add Account",
        moduleName: "add-account",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "/account/update-profile",
    title: "Account Settings",
    moduleName: "admin",
    iconType: "feather",
    icon: "settings",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },

  //Technical Evaluators

  {
    path: "/technical-evaluator/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_TECHNICAL"],
    submenu: [],
  },

  {
    path: "",
    title: "Tenders",
    moduleName: "teender",
    iconType: "feather",
    icon: "folder-plus",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_TECHNICAL"],
    submenu: [
      {
        path: "/commons/tender/pending-tenders",
        title: "Pending Tenders",
        moduleName: "pending-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/technical-evaluator/tender/approved-tenders",
        title: "Approved Tenders",
        moduleName: "approved-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ],
  },

  {
    path: "",
    title: "RFQs Applications",
    moduleName: "rfq-applications",
    iconType: "feather",
    icon: "git-pull-request",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_TECHNICAL"],
    submenu: [
      {
        path: "/commons/rfqs/approved-rfq-applications",
        title: "Approved Applications",
        moduleName: "approved-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/commons/rfqs/system-evaluated-rfq-applications",
        title: "Evaluated Applications",
        moduleName: "system-evaluated-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/commons/rfqs/rejected-rfq-applications",
        title: "Rejected Applications",
        moduleName: "rejected-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ],
  },

  {
    path: "/admin/reports/all",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "edit",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_TECHNICAL"],
    submenu: [],
  },





  // Financial Evaluators

  {
    path: "/financial-evaluator/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_FINANCIAL"],
    submenu: [],
  },

  {
    path: "",
    title: "Tenders",
    moduleName: "teender",
    iconType: "feather",
    icon: "folder-plus",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_FINANCIAL"],
    submenu: [
      {
        path: "/commons/tender/pending-tenders",
        title: "Pending Tenders",
        moduleName: "pending-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/financial-evaluator/tender/approved-tenders",
        title: "Approved Tenders",
        moduleName: "approved-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ],
  },

  {
    path: "",
    title: "RFQs",
    moduleName: "rfqs",
    iconType: "feather",
    icon: "git-pull-request",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_FINANCIAL"],
    submenu: [
      {
        path: "/financial-evaluator/rfqs/pending-rfqs",
        title: "Pending RFQs",
        moduleName: "pending-rfqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/financial-evaluator/rfqs/approved-rfqs",
        title: "Approved RFQs",
        moduleName: "approved-rfqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/financial-evaluator/rfqs/rejected-rfqs",
        title: "Rejected RFQs",
        moduleName: "rejected-rfqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      // {
      //   path: "/financial-evaluator/rfqs/open-rfqs",
      //   title: "Open RFQs",
      //   moduleName: "opened-rfqs",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
      // {
      //   path: "/financial-evaluator/rfqs/closed-rfqs",
      //   title: "Closed RFQs",
      //   moduleName: "closed-rfqs",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
    ],
  },
  {
    path: "",
    title: "RFQs Applications",
    moduleName: "rfq-applications",
    iconType: "feather",
    icon: "git-pull-request",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_FINANCIAL"],
    submenu: [
      {
        path: "/financial-evaluator/rfqs/pending-rfq-applications",
        title: "Pending Applications",
        moduleName: "pending-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/commons/rfqs/approved-rfq-applications",
        title: "Approved Applications",
        moduleName: "approved-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/commons/rfqs/system-evaluated-rfq-applications",
        title: "Evaluated Applications",
        moduleName: "system-evaluated-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/commons/rfqs/rejected-rfq-applications",
        title: "Rejected Applications",
        moduleName: "rejected-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ],
  },

  

  {
    path: "/financial-evaluator/reports/all",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "edit",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_FINANCIAL"],
    submenu: [],
  },


  // Desk Evaluators

  {
    path: "/desk-evaluator/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_DESK"],
    submenu: [],
  },


  {
    path: "",
    title: "Tenders",
    moduleName: "teender",
    iconType: "feather",
    icon: "folder-plus",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_DESK"],
    submenu: [
      {
        path: "/commons/tender/pending-tenders",
        title: "Pending Tenders",
        moduleName: "pending-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/desk-evaluator/tender/approved-tenders",
        title: "Approved Tenders",
        moduleName: "approved-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ],
  },

  {
    path: "",
    title: "Tenders Adverts",
    moduleName: "tender-adverts",
    iconType: "feather",
    icon: "cast",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_DESK"],
    submenu: [
      {
        path: "/desk-evaluator/tender/pending-tender-adverts",
        title: "Pending Tender Adverts",
        moduleName: "pending-tender-adverts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/desk-evaluator/tender/approved-tender-adverts",
        title: "Approved Tender Adverts",
        moduleName: "approved-tender-adverts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/desk-evaluator/tender/rejected-tender-adverts",
        title: "Rejected Tender Adverts",
        moduleName: "rejected-tender-adverts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ],
  },

  {
    path: "/desk-evaluator/reports/all",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "edit",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_DESK"],
    submenu: [],
  },

  //Head Of Departments
  // {
  //   path: "",
  //   title: "MAIN",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_HEAD"],
  //   submenu: [],
  // },

  {
    path: "/departmental-users/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_HEAD"],
    submenu: [],
  },

  // {
  //   path: "",
  //   title: "NEEDS MANAGEMENT",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_HEAD"],
  //   submenu: [],
  // },

  {
    path: "",
    title: "Need Management",
    moduleName: "need",
    iconType: "feather",
    icon: "umbrella",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_HEAD"],
    submenu: [
      {
        path: "/departmental-users/need-management/need-requisition-form",
        title: "Request Need",
        moduleName: "request-need",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/departmental-users/need-management/pending-needs",
        title: "Pending Needs",
        moduleName: "pending-needs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/departmental-users/need-management/approved-needs",
        title: "Approved Needs",
        moduleName: "approved-needs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      // {
      //   path: "/departmental-users/need-management/full-filled-needs",
      //   title: "Fullfilled Needs",
      //   moduleName: "full-filled-need",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
      {
        path: "/departmental-users/need-management/full-filled-needs",
        title: "Rejected Needs",
        moduleName: "rejected-needs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  // Supplier details

  {
    path: "/suppliers/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_SUPPLIER"],
    submenu: [],
  },
  {
    path: "",
    title: "Parameters",
    moduleName: "parameters",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_SUPPLIER"],
    submenu: [
      {
        path: "/suppliers/parameters/general",
        title: "General",
        moduleName: "parameters",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      
    ],
  },
  // applications-sent
  {
    path: "/suppliers/prequalifications",
    title: "Prequalifications",
    moduleName: "prequalifications",
    iconType: "feather",
    icon: "slack",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_SUPPLIER"],
    submenu: [
      {
        path: "/suppliers/prequalifications/apply",
        title: "Apply for prequalification",
        moduleName: "prequalifications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/suppliers/prequalifications/applications-sent",
        title: "Applications sent",
        moduleName: "prequalifications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "RFQS Applications",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "star",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_SUPPLIER"],
    submenu: [
      {
        path: "/suppliers/rfqs/open-rfqs",
        title: "Open RFQs",
        moduleName: "open-rfqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/suppliers/rfqs/pending-rfq-applications",
        title: "Pending Applications",
        moduleName: "pending-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/suppliers/rfqs/approved-rfq-applications",
        title: "Approved Applications",
        moduleName: "approved-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/suppliers/rfqs/unsuccessful-rfq-applications",
        title: "Unsuccessful Applications",
        moduleName: "unsuccessful-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "/suppliers/tenders",
    title: "Tenders",
    moduleName: "tenders",
    iconType: "feather",
    icon: "slack",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_SUPPLIER"],
    submenu: [
      {
        path: "/suppliers/tenders/all-posted-tenders",
        title: "All posted tenders",
        moduleName: "tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/suppliers/tenders/applications-sent",
        title: "Applications sent",
        moduleName: "tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  // {
  //   path: "/suppliers/asset-disposal",
  //   title: "Asset Disposal",
  //   moduleName: "dashboard",
  //   iconType: "feather",
  //   icon: "database",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_SUPPLIER"],
  //   submenu: [],
  // },
  // {
  //   path: "/suppliers/risk-management",
  //   title: "Risk Management",
  //   moduleName: "dashboard",
  //   iconType: "feather",
  //   icon: "command",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_SUPPLIER"],
  //   submenu: [],
  // },

  {
    path: "/suppliers/reports",
    title: "Reports",
    moduleName: "reports",
    iconType: "feather",
    icon: "book",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_SUPPLIER"],
    submenu: [],
  },

  // Procurement admin
  {
    path: "/procurement-admin/dashboard",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [],
  },
  {
    path: "/procurement-admin/parameters/tax",
    title: "Tax Parameters",
    moduleName: "tender",
    iconType: "feather",
    icon: "file-text",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [],
  },
  // {
  //   path: "",
  //   title: "Prequalification management",
  //   moduleName: "",
  //   iconType: "",
  //   icon: "",
  //   class: "",
  //   groupTitle: true,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_PROCUREMENT_ADMIN", "ROLE_DESK"],
  //   submenu: [],
  // },
  {
    path: "/procurement-admin/announce",
    title: "Announce prequalification",
    moduleName: "announce",
    iconType: "feather",
    icon: "grid",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN", "ROLE_DESK"],
    submenu: [
      {
        path: "/procurement-admin/announce/add",
        title: "Add",
        moduleName: "announce",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/announce/pending",
        title: "Pending",
        moduleName: "announce",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/announce/partially-verified",
        title: "Partial",
        moduleName: "announce",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/announce/approved",
        title: "Approved",
        moduleName: "announce",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/announce/rejected",
        title: "Rejected",
        moduleName: "announce",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },{
        path: "/procurement-admin/announce/deleted-announcements",
        title: "Deleted",
        moduleName: "announce",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/procurement-admin/recieved-applications",
    title: "Prequalification Applications",
    moduleName: "recieve-applications",
    iconType: "feather",
    icon: "edit",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [
      
      {
        path: "/procurement-admin/recieved-applications/pending",
        title: "Pending",
        moduleName: "recieve-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/recieved-applications/approved",
        title: "Approved",
        moduleName: "recieve-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/recieved-applications/rejected",
        title: "Rejected",
        moduleName: "recieve-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/procurement-admin/prequalified-suppliers/",
    title: "Prequalified Suppliers",
    moduleName: "prequalified-suppliers",
    iconType: "feather",
    icon: "user-check",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [
      
      {
        path: "/procurement-admin/prequalified-suppliers/all-prequalified",
        title: "Prequalified",
        moduleName: "prequalified-suppliers",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      
    ],
  },

  {
    path: "",
    title: "Needs Management",
    moduleName: "need",
    iconType: "feather",
    icon: "umbrella",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [
      {
        path: "/procurement-admin/needs/pending-needs",
        title: "Pending Needs",
        moduleName: "pending-needs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/needs/approved-needs",
        title: "Approved Needs",
        moduleName: "approved-needs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      // {
      //   path: "/procurement-admin/needs/full-filled-needs",
      //   title: "Fullfilled Needs",
      //   moduleName: "full-filled-need",
      //   iconType: "",
      //   icon: "",
      //   class: "ml-menu",
      //   groupTitle: false,
      //   badge: "",
      //   badgeClass: "",
      //   role: [""],
      //   submenu: [],
      // },
      {
        path: "/procurement-admin/needs/rejected-needs",
        title: "Rejected Needs",
        moduleName: "rejected-needs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "/procurement-admin/tender-requirements/mandatory-requirements",
    title: "Tender Requirements",
    moduleName: "tender-requirements",
    iconType: "feather",
    icon: "layout",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [],
  },

  {
    path: "/procurement-admin/tender/tender-categories",
    title: "Tender categories",
    moduleName: "tender",
    iconType: "feather",
    icon: "file-text",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [],
  },
  {
    path: "/procurement-admin/terms-and-conditions",
    title: "Terms and Conditions",
    moduleName: "terms",
    iconType: "feather",
    icon: "copy",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [],
  },

  {
    path: "",
    title: "Tender Preperation",
    moduleName: "teender",
    iconType: "feather",
    icon: "folder-plus",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [
      {
        path: "/procurement-admin/tender/prepare-tender",
        title: "Prepare Tender",
        moduleName: "prepare-tender",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/tender/pending-tenders",
        title: "Pending Tenders",
        moduleName: "pending-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/tender/approved-tenders",
        title: "Approved Tenders",
        moduleName: "aproved-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/tender/posted-tenders",
        title: "Posted Tenders",
        moduleName: "posted-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/tender/rejected-tenders",
        title: "Rejected Tenders",
        moduleName: "rejected-tenders",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "Tender Adverts",
    moduleName: "tender-adverts",
    iconType: "feather",
    icon: "cast",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [
      {
        path: "/procurement-admin/tender/generate-tender-advert",
        title: "Genarate Advert",
        moduleName: "generate-tender-advert",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/tender/pending-tender-adverts",
        title: "Pending Tender Adverts",
        moduleName: "pending-tender-adverts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/tender/approved-tender-adverts",
        title: "Approved Tender Adverts",
        moduleName: "approved-tender-adverts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/tender/rejected-tender-adverts",
        title: "Rejected Tender Adverts",
        moduleName: "rejected-tender-adverts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ],
  },


 
  

  // {
  //   path: "/procurement-admin/prequalifications/preq-categories",
  //   title: "Prequalification parameters",
  //   moduleName: "prequalifications",
  //   iconType: "feather",
  //   icon: "slack",
  //   class: "",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["ROLE_PROCUREMENT_ADMIN"],
  //   submenu: [],
  // },

 
  {
    path: "",
    title: "RFQs",
    moduleName: "rfqs",
    iconType: "feather",
    icon: "git-pull-request",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [
      {
        path: "/procurement-admin/rfqs/create-rfq",
        title: "Create RFQ",
        moduleName: "create-rfq",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/rfqs/pending-rfqs",
        title: "Pending RFQs",
        moduleName: "pending-rfqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/rfqs/approved-rfqs",
        title: "Approved RFQs",
        moduleName: "approved-rfqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/rfqs/posted-rfqs",
        title: "Posted RFQs",
        moduleName: "posted-rfqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/rfqs/rejected-rfqs",
        title: "Rejected RFQs",
        moduleName: "rejected-rfqs",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  {
    path: "/procurement-admin/contract-management/",
    title: "Contracts",
    moduleName: "contract-management",
    iconType: "feather",
    icon: "book-open",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN","ROLE_TECHNICAL","ROLE_DESK","ROLE_FINANCIAL"],
    submenu: [
      {
        path: "/procurement-admin/contract-management/add-contract",
        title: "Add Contract",
        moduleName: "contract-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/contract-management/pending-contracts",
        title: "Pending Contracts",
        moduleName: "contract-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/contract-management/approved-contracts",
        title: "Approved Contracts",
        moduleName: "contract-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/contract-management/rejected-contracts",
        title: "Rejected Contracts",
        moduleName: "contract-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/contract-management/deleted-contracts",
        title: "Deleted Contracts",
        moduleName: "contract-management",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      
    ],
  },

  {
    path: "",
    title: "RFQs Applications",
    moduleName: "rfq-applications",
    iconType: "feather",
    icon: "git-pull-request",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [
      {
        path: "/commons/rfqs/approved-rfq-applications",
        title: "Approved Applications",
        moduleName: "approved-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/commons/rfqs/system-evaluated-rfq-applications",
        title: "Evaluated Applications",
        moduleName: "system-evaluated-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/commons/rfqs/rejected-rfq-applications",
        title: "Rejected Applications",
        moduleName: "rejected-rfq-applications",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      }
    ],
  },

  {
    path: "",
    title: "Bidders Accounts",
    moduleName: "bidders",
    iconType: "feather",
    icon: "user",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_PROCUREMENT_ADMIN"],
    submenu: [
      {
        path: "/procurement-admin/bidders/all-bidders",
        title: "All Bidders",
        moduleName: "active-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/procurement-admin/bidders/inactive-accounts",
        title: "Inactive Accounts",
        moduleName: "inactive-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "procurement-admin/bidders/locked-accounts",
        title: "Locked Accounts",
        moduleName: "locked-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "procurement-admin/bidders/deleted-accounts",
        title: "Deleted Accounts",
        moduleName: "deleted-accounts",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
];
